config.c: enforce stricter parsing of config files
logrotate/logrotate pull request #427
Opened 2021-10-21 11:01 UTC by felixwilhelm

A number of recent exploits have abused logrotate's lax parsing of config files as an easy way to turn privileged file write bugs into code execution:
- https://alephsecurity.com/2021/10/20/sudump/
- https://flattsecurity.medium.com/cve-2020-15702-race-condition-vulnerability-in-handling-of-pid-by-apport-4047f2e00a67#e688
- https://alephsecurity.com/2021/02/16/apport-lpe/

These exploits depend on bugs in other parts of the OS (apport, kernel, ..) to write partially controlled files to the logrotate config directory. Targeting logrotate is highly useful for attackers, because it will ignore invalid parts of config files and continue parsing until it finds a valid configuration.
This behaviour makes exploitation of tricky bugs such as the linked coredump vulnerabilities much easier.

This PR enforces stricter parsing of config files, by turning some of the already existing parser warnings into hard errors. It does not have any effect on users using valid configuration files, but might be a breaking change for people relying on the current handling of invalid files. As current versions already print an error message when encountering such files, no widely used configurations should be affected. 

Overall, I think this would be a nice defense-in-depth change to improve the security of many downstream logrotate users.

2021-11-01 14:21 UTC, felixwilhelm commented
@kdudka friendly ping.

2021-11-01 14:39 UTC, kdudka commented
Sorry for the delay!  I was on vacation last week.  The proposed changes look fair to me.  I would appreciate an additional review by @cgzones though.  He is the original author of the `keyword ... not properly separated` diagnostic message (and the most active contributor of logrotate these days).

2021-11-02 18:49 UTC, cgzones requested changes
Please add test cases for the following configurations:

```
&DIR&/test1.log {
    newkeyword
}
&DIR&/test2.log {
    rotate 1
}
```
and check that test1.log has not been rotated, but test2.log.

```
&DIR&/test1.log {
    g@rbag€[]+#*
}
&DIR&/test2.log {
    rotate 1
}
```
and check that both test1.log and test2.log have not been rotated.

2021-11-02 18:49 UTC, cgzones commented on config.c
> +                    RAISE_ERROR();
I think in this case we want to abort reading the whole file and not parse any potential following blocks, so `goto error;` would be more appropriate.

2021-11-02 18:49 UTC, cgzones commented on test/test-0102.sh
> +if [ $? -eq 0 ]; then
Please also check that `test.log` has not been rotated.

2021-11-02 18:49 UTC, cgzones commented on test/test-0103.sh
> +if [ $? -eq 0 ]; then
Please also check that `test.log` has not been rotated.

2021-11-03 08:04 UTC, kdudka commented
@cgzones My proposal was actually not to treat unknown configuration directives as errors that would prevent log files from being rotated.  logrotate configuration files are often updated independently of logrotate itself and their compatibility with older logrotate releases is important in my opinion.

2021-11-04 19:02 UTC, cgzones commented on config.c
> +                    RAISE_ERROR();
> My proposal was actually not to treat unknown configuration directives as errors that would prevent log files from being rotated. logrotate configuration files are often updated independently of logrotate itself and their compatibility with older logrotate releases is important in my opinion.

true, so my comment was void.

2021-12-17 15:50 UTC, cgzones commented
@kdudka since you approved #431, can I merge this one here and afterwards apply the test suite changes?

2021-12-20 14:20 UTC, kdudka commented
Definitely.  Thank you for taking care of it!

2021-12-20 17:16 UTC, merged

2021-12-20 17:16 UTC, cgzones commented
Applied, thanks for the contribution.

2022-01-05 12:36 UTC, felixwilhelm commented
Thanks for pushing this through! 👍