Make wait() checks more reliable
logrotate/logrotate pull request #616
Opened 2024-06-20 15:11 UTC by Aparicio99

**Reasoning** 

I've caught an issue where pre/post rotate scripts were being reported with an error "error running non-shared prerotate script for...", but only on very specific but deterministic conditions. After some debugging I've found it to be due to on my use case logrotate being launched from crond which had already inherited from its parent to ignore SIGCHLD.

Even in this situation, the issue depended on compiler optimization flags, and even on moving/deleting non related code around, which eventually found to be due to the uninitialized use of the wait() return argument, therefore the changes I propose for every use of wait()/waitpid().

---
**Commit message**

If wait()/waitpid() returns an error for some reason it will not write to the *wstatus argument. Checking wstatus in this case is non deterministic due to the variable not being initialized, and may lead to wrongly report the forked command as executed successfully.

Also, one possible reason for wait() to return an error even if the forked command has executed successfully is the child process exiting before we call wait(). Normally when the child process finishes it stays in a zombie state until the wait() call, but if our parent process has set to ignore the SIGCHLD signal, we will inherited it and our child processes will exit immediately. Restoring the signal handler on initialization will avoid this issue.

2024-06-23 13:17 UTC, cgzones requested changes
Thanks, looks good to me except one small nit.

2024-06-23 13:17 UTC, cgzones commented on logrotate.c
> +    signal(SIGCHLD, SIG_DFL);
Please issue a warning on failure, e.g.:
```c
if (signal(SIGCHLD, SIG_DFL) == SIG_ERR)
    message(MESS_WARN, "failed to reset SIGCHLD handler: %s\n", strerror(errno));
```

2024-06-24 10:54 UTC, Aparicio99 commented on logrotate.c
> +    signal(SIGCHLD, SIG_DFL);
Updated with your suggestion.

2024-07-07 06:09 UTC, cgzones reviewed
I'd like to take this opportunity and replace the `wait(3)` calls with `waitpid(3)`.
Also the `waitpid(3)` call on line 1112 is not checked.

2024-07-07 06:09 UTC, cgzones commented on logrotate.c
> +    if (wait(&rc) > 0 && WIFEXITED(rc)) {
Could you please take this opportunity and replace with `wait(3)` with `waitpid(3)`.
```c
waitpid(pid, &rc, 0);
```

2024-07-07 06:09 UTC, cgzones commented on logrotate.c
> +    if (wait(&status) < 0 || !WIFEXITED(status) || WEXITSTATUS(status)) {
```c
waitpid(pid, &status, 0);
```

2024-07-07 06:09 UTC, cgzones commented on logrotate.c
> +    if (wait(&status) < 0 || !WIFEXITED(status) || WEXITSTATUS(status)) {
```c
waitpid(pid, &status, 0);
```

2024-07-08 14:39 UTC, Aparicio99 commented
Replaced all wait() calls with waitpid() and added validation of all return codes.

strerror(errno) can also be added to the error messages, but since it would only apply to when waitpid() fails and not when "!WIFEXITED(status) || WEXITSTATUS(status)" is true, it would complicate the code and possible have 2 different error messages for each call. Not sure if it's worth it, but I could also add this if you think so.

2024-07-14 09:46 UTC, cgzones commented
> Replaced all wait() calls with waitpid() and added validation of all return codes.

Thanks.

> strerror(errno) can also be added to the error messages, but since it would only apply to when waitpid() fails and not when "!WIFEXITED(status) || WEXITSTATUS(status)" is true, it would complicate the code and possible have 2 different error messages for each call. Not sure if it's worth it, but I could also add this if you think so.

What about a helper like:

```c
int waitpid_checked(pid_t pid, const char **errmsg) {
    int r, status;

    r = waitpid(pid, &status, 0);
    if (r <= 0) {
        *errmsg = strerror(errno);
        return -1;
    }

    if (!WIFEXITED(status)) {
        *errmsg = "child did not terminate normally";
        return -1;
    }

    if (WEXITSTATUS(status) != 0) {
        *errmsg = "child did not exit with status 0";
        return -1;
    }

    *errmsg = NULL;
    return 0;
}
```
?

2024-07-19 15:31 UTC, Aparicio99 commented
Implemented the helper as you suggested. Also updated runScript and callers to use the helper error message.

2024-07-27 09:43 UTC, cgzones approved these changes

2024-07-27 09:44 UTC, merged

2024-07-27 09:45 UTC, cgzones commented
Applied. Thanks for your contribution and the patch iterations.